# See .github/workflows/CheckBadMerge.groovy for explanation
name: Check bad merge commit
on:
  pull_request:
    types: [ opened ]

jobs:
  check_pr_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install Groovy
        run: sudo apt-get install groovy
      - name: List PR commits
        run: |
          git fetch origin
          git log --pretty=format:"%H" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > pr_commits.txt
      - name: Check PR commits
        id: run_check
        run: |
          pr_commits=$(cat pr_commits.txt)
          groovy .github/workflows/CheckReleaseNoteInMergeCommit.groovy $pr_commits > output.txt || echo "Groovy check failed."
      - name: Read output file
        id: read_output
        run: |
          cat output.txt
        continue-on-error: true
      - name: Comment on PR if check failed
        if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            Some bad merge is found:
            \`\`\`
            ${{ steps.read_output.outputs.stdout }}
            \`\`\`
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
